### ISSUE TITLE
Missing LICENSE.txt

### ISSUE THREAD

**Issue by elliotwutingfeng** [nextcloud/NextcloudKit#65]
Link to `LICENSE.txt` on [README.md](https://github.com/nextcloud/NextcloudKit/blob/main/README.md) is missing.

> https://github.com/nextcloud/NextcloudKit/blob/main/LICENSE.txt

Same goes for

> https://github.com/nextcloud/NextcloudKit/blob/main/COPYING.iOS

**Comment by elliotwutingfeng** [comment]
Thanks for the update. This issue was opened in Apr 2024 when the links were dead in the readme (https://github.com/nextcloud/NextcloudKit/blob/7165f52cf485902a86a879a20a854ff6d1008766/README.md).

**Comment by AndyScherzinger** [comment]
Yes, the files have been missing themselves and got added 3 months ago via https://github.com/nextcloud/NextcloudKit/commit/ef859ec11edbfba3917ae27af338520729222345

This than made the links work 👍

Thanks for bringing it up back than.

I just checked it now and closed the ticket since it is working now.
